version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: secure-login-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - secure-login-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: secure-login-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - secure-login-network

volumes:
  mongodb_data:

networks:
  secure-login-network:
    driver: bridge

